/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectPhotosRouteImport } from './routes/project-photos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PartnerProfileRouteImport } from './routes/partner-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IndexRouteImport } from './routes/index'

const ProjectPhotosRoute = ProjectPhotosRouteImport.update({
  id: '/project-photos',
  path: '/project-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/partner-profile',
  path: '/partner-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/pipeline': typeof PipelineRoute
  '/project-photos': typeof ProjectPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/pipeline': typeof PipelineRoute
  '/project-photos': typeof ProjectPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/partner-profile': typeof PartnerProfileRoute
  '/pipeline': typeof PipelineRoute
  '/project-photos': typeof ProjectPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/login'
    | '/partner-profile'
    | '/pipeline'
    | '/project-photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/login'
    | '/partner-profile'
    | '/pipeline'
    | '/project-photos'
  id:
    | '__root__'
    | '/'
    | '/leads'
    | '/login'
    | '/partner-profile'
    | '/pipeline'
    | '/project-photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PipelineRoute: typeof PipelineRoute
  ProjectPhotosRoute: typeof ProjectPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-photos': {
      id: '/project-photos'
      path: '/project-photos'
      fullPath: '/project-photos'
      preLoaderRoute: typeof ProjectPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-profile': {
      id: '/partner-profile'
      path: '/partner-profile'
      fullPath: '/partner-profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PipelineRoute: PipelineRoute,
  ProjectPhotosRoute: ProjectPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
