import { Employee, Client, CallRecord, CallStatus } from '@/types';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'MAP_001',
    name: 'Ravi Kumar',
    password: 'pass123',
    role: 'mapping',
    avatar: 'RK',
    department: 'Field Mapping',
    phone: '+91 98765 43210',
    joinDate: '2023-06-01',
    stats: {
      totalCalls: 0,
      successRate: 0,
      thisMonth: 0,
    },
  },
  {
    id: 'MAP_002',
    name: 'Sneha Patel',
    password: 'pass123',
    role: 'mapping',
    avatar: 'SP',
    department: 'Field Mapping',
    phone: '+91 91234 56789',
    joinDate: '2024-01-15',
    stats: {
      totalCalls: 0,
      successRate: 0,
      thisMonth: 0,
    },
  },
  {
    id: 'VIB_001',
    name: 'Alex Johnson',
    password: 'pass123',
    role: 'Senior Sales Executive',
    avatar: 'AJ',
    department: 'Enterprise Sales',
    phone: '+1 (555) 001-0001',
    joinDate: '2022-03-15',
    stats: {
      totalCalls: 1284,
      successRate: 68,
      thisMonth: 87,
    },
  },
  {
    id: 'VIB_002',
    name: 'Sarah Mitchell',
    password: 'pass123',
    role: 'Sales Executive',
    avatar: 'SM',
    department: 'SMB Sales',
    phone: '+1 (555) 001-0002',
    joinDate: '2023-01-10',
    stats: {
      totalCalls: 743,
      successRate: 72,
      thisMonth: 63,
    },
  },
];

const today = new Date().toISOString().split('T')[0];

export const MOCK_CLIENTS: Record<string, Client[]> = {
  VIB_001: [
    {
      id: 'CLT_001',
      name: 'Marcus Webb',
      company: 'TechCorp Industries',
      phone: '+1 (555) 210-3344',
      email: 'marcus.webb@techcorp.com',
      industry: 'Technology',
      value: '$45,000',
      scheduledTime: '09:00 AM',
      location: 'Whitefield, Bengaluru',
      priority: 'high',
      notes: 'Follow up on Q1 proposal. Interested in enterprise plan.',
      status: 'pending',
      lastContact: '2026-04-05',
      callHistory: [],
    },
    {
      id: 'CLT_002',
      name: 'Diana Rosales',
      company: 'Bloom Retail Group',
      phone: '+1 (555) 387-9920',
      email: 'diana.r@bloomretail.com',
      industry: 'Retail',
      value: '$12,000',
      scheduledTime: '10:30 AM',
      location: 'Koramangala, Bengaluru',
      priority: 'medium',
      notes: 'Demo scheduled. Needs pricing details for 50 users.',
      status: 'pending',
      lastContact: '2026-04-03',
      callHistory: [],
    },
    {
      id: 'CLT_003',
      name: 'James Thornton',
      company: 'Apex Logistics',
      phone: '+1 (555) 456-7788',
      email: 'j.thornton@apexlogistics.com',
      industry: 'Logistics',
      value: '$78,500',
      scheduledTime: '11:15 AM',
      location: 'Indiranagar, Bengaluru',
      priority: 'high',
      notes: 'Hot lead. CEO wants to finalize contract by end of month.',
      status: 'pending',
      lastContact: '2026-04-07',
      callHistory: [],
    },
    {
      id: 'CLT_004',
      name: 'Priya Nair',
      company: 'Stellar Health',
      phone: '+1 (555) 123-5566',
      email: 'priya.nair@stellarhealth.com',
      industry: 'Healthcare',
      value: '$23,000',
      scheduledTime: '01:00 PM',
      location: 'Hebbal, Bengaluru',
      priority: 'medium',
      notes: 'Compliance team review pending. Check on update.',
      status: 'pending',
      lastContact: '2026-03-28',
      callHistory: [],
    },
    {
      id: 'CLT_005',
      name: 'Ryan Okafor',
      company: 'NextGen Finance',
      phone: '+1 (555) 678-2200',
      email: 'ryan.o@nextgenfinance.com',
      industry: 'Finance',
      value: '$31,000',
      scheduledTime: '02:30 PM',
      location: 'MG Road, Bengaluru',
      priority: 'low',
      notes: 'Initial contact. Sent brochure last week.',
      status: 'pending',
      lastContact: '2026-04-01',
      callHistory: [],
    },
    {
      id: 'CLT_006',
      name: 'Lena Hoffmann',
      company: 'EduSpark Academy',
      phone: '+1 (555) 900-4433',
      email: 'lena.h@eduspark.edu',
      industry: 'Education',
      value: '$8,500',
      scheduledTime: '03:45 PM',
      location: 'Yelahanka, Bengaluru',
      priority: 'low',
      notes: 'Budget approval expected this week.',
      status: 'pending',
      lastContact: '2026-04-06',
      callHistory: [],
    },
    {
      id: 'CLT_007',
      name: 'Carlos Mendez',
      company: 'Urban Build Co.',
      phone: '+1 (555) 333-8877',
      email: 'carlos@urbanbuild.com',
      industry: 'Construction',
      value: '$55,000',
      scheduledTime: '04:30 PM',
      location: 'Electronic City, Bengaluru',
      priority: 'high',
      notes: 'Referral from James Thornton. Very interested.',
      status: 'pending',
      lastContact: '2026-04-08',
      callHistory: [],
    },
  ],
  VIB_002: [
    {
      id: 'CLT_101',
      name: 'Olivia Grant',
      company: 'Spark Media',
      phone: '+1 (555) 210-1122',
      email: 'olivia@sparkmedia.com',
      industry: 'Media',
      value: '$15,000',
      scheduledTime: '09:30 AM',
      location: 'Bandra West, Mumbai',
      priority: 'medium',
      notes: 'Interested in yearly plan. Negotiate discount.',
      status: 'pending',
      lastContact: '2026-04-04',
      callHistory: [],
    },
    {
      id: 'CLT_102',
      name: 'Tom Bradley',
      company: 'FreshFood Co.',
      phone: '+1 (555) 445-6600',
      email: 'tom.b@freshfood.com',
      industry: 'Food & Beverage',
      value: '$9,200',
      scheduledTime: '11:00 AM',
      location: 'Andheri East, Mumbai',
      priority: 'low',
      notes: 'Third follow-up. Lukewarm interest.',
      status: 'pending',
      lastContact: '2026-03-30',
      callHistory: [],
    },
  ],
};

export const CALL_STATUSES: CallStatus[] = [
  { key: 'pending', label: 'Pending', icon: 'schedule', color: '#F59E0B', description: 'Not yet contacted' },
  { key: 'no-response', label: 'No Response', icon: 'phone-missed', color: '#F59E0B', description: 'Client did not pick up' },
  { key: 'not-interested', label: 'Not Interested', icon: 'thumb-down', color: '#EF4444', description: 'Client not interested' },
  { key: 'qualified', label: 'Qualified', icon: 'check-circle', color: '#10B981', description: 'Lead qualified' },
  { key: 'number-inactive', label: 'Number Inactive', icon: 'phone-disabled', color: '#9CA3AF', description: 'Phone number inactive' },
  { key: 'number-switched-off', label: 'Switched Off', icon: 'phone-locked', color: '#EF4444', description: 'Phone switched off' },
  { key: 'on-hold', label: 'On Hold', icon: 'pause-circle-filled', color: '#3B82F6', description: 'Client asked to hold' },
  { key: 'no-requirement', label: 'No Requirement', icon: 'cancel', color: '#6B7280', description: 'No current requirement' },
  { key: 'follow-up', label: 'Follow Up', icon: 'schedule', color: '#06B6D4', description: 'Needs follow-up' },
  { key: 'disqualified', label: 'Disqualified', icon: 'block', color: '#DC2626', description: 'Lead disqualified' },
  { key: 'disconnected', label: 'Disconnected', icon: 'phone-disabled', color: '#991B1B', description: 'Call disconnected' },
  { key: 'already-finalised', label: 'Already Finalised', icon: 'done-all', color: '#059669', description: 'Already finalized' },
];

export const getStatusColor = (status: string): string => {
  const map: Record<string, string> = {
    pending: '#F59E0B',
    'no-response': '#F59E0B',
    'not-interested': '#EF4444',
    qualified: '#10B981',
    'number-inactive': '#9CA3AF',
    'number-switched-off': '#EF4444',
    'on-hold': '#3B82F6',
    'no-requirement': '#6B7280',
    'follow-up': '#06B6D4',
    disqualified: '#DC2626',
    disconnected: '#991B1B',
    'already-finalised': '#059669',
  };
  return map[status] || '#374151';
};

export const getStatusBg = (status: string): string => {
  const map: Record<string, string> = {
    pending: 'rgba(245, 158, 11, 0.12)',
    'no-response': 'rgba(245, 158, 11, 0.12)',
    'not-interested': 'rgba(239, 68, 68, 0.12)',
    qualified: 'rgba(16, 185, 129, 0.12)',
    'number-inactive': 'rgba(156, 163, 175, 0.12)',
    'number-switched-off': 'rgba(239, 68, 68, 0.12)',
    'on-hold': 'rgba(59, 130, 246, 0.12)',
    'no-requirement': 'rgba(107, 114, 128, 0.12)',
    'follow-up': 'rgba(6, 182, 212, 0.12)',
    disqualified: 'rgba(220, 38, 38, 0.12)',
    disconnected: 'rgba(153, 27, 27, 0.12)',
    'already-finalised': 'rgba(5, 150, 105, 0.12)',
  };
  return map[status] || 'rgba(55, 65, 81, 0.2)';
};

export const getStatusLabel = (status: string): string => {
  const found = CALL_STATUSES.find(s => s.key === status);
  return found ? found.label : 'Pending';
};
